### PR TITLE
Added Slash => Z KeyMapping

### PR DESCRIPTION
**Pull request by nygellyndley**
Not sure if this is a bug or intentional, and it's difficult to get feedback in the Core discord on CoreConverter changes.

Running the current code throught the Google Drive files as seeds results in an invalid Right hand layout.

Specifically a `Cancel` and `Rally` conflict.

It's caused by a missing mapping back from `Slash` to `Z`, fixed in this PR.

It's not clear to me whether this is intentional though, this may have been absent due to some conflict on some mapping, though on the face of it the relationship does seem like it should be a one to one.

Added PR for you to assess.

### CODE REVIEW

**Comment by nygellyndley** [comment]
Added a second change here.

Reordered mappings file alphabetically.

Included the following for L/R mapping :
```
CommanderAbility0=1
CommanderAbility1=1
CommanderAbility2=1
CommanderAbility3=1
```

Excluded the following from L/R mapping :
```
ChatAllies
ChatDefault
ChatIndividual
ChatRecipient
```

**Comment by nygellyndley** [comment]
Added `ChatAllies` back in.

`ChatAllies` should really not L/R map but it currently causes a conflict, on camera rotation.
The behaviour of LRing Default, Individual, Recipient but not Allies matches what is currently in the drive.

**Comment by michaelnew** [comment]
Hey thanks for the PR. Sorry for not looking at it sooner. Couple questions/thoughts:
* The source files went from around 450 lines to over 1200. What's in there? Co-op bindings?

**Comment by michaelnew** [comment]
Hey thanks for the PR. Sorry for not looking at it sooner. Couple questions/thoughts:
* The source files went from around 450 lines to over 1200. What's in there? Co-op bindings?
* Have you talked with jakatak (or someone like him) about these changes?
* Are we releasing The Core 5.0?

**Comment by nygellyndley** [comment]
Hi, maybe I should close this PR.

There is some discussion in the Discord about how to deal with the repo going forward : https://discordapp.com/channels/389438169520799744/513669112589844480

Core 5 was released a while back, it's in the Google Drive.

**Comment by michaelnew** [comment]
@nygellyndley that link doesn't work for me. Can you just invite me to the server? mikenew#1843

**Comment by nygellyndley** [comment]
this work? https://discord.gg/Y5Jrr2

**Pull request merged**
